var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/dogs/[dogId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__17a5e246._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_2163dabf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c57189c0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_3fd7cd9c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_dogs_[dogId]_page_actions_01ad8322.js")
R.m(84551)
module.exports=R.m(84551).exports
