import type { DogBreedLookup } from "@/lib/thedogapi"

export const CURATED_FALLBACK_BREEDS: DogBreedLookup[] = [
  {
    id: "border-collie",
    name: "Border Collie",
    breedGroup: "Herding",
    origin: "Reino Unido",
    temperament: "Intelligent, Energetic, Alert, Responsive, Trainable",
    description: "Raca extremamente inteligente, veloz e orientada ao trabalho. Precisa de desafio mental e rotina ativa.",
    lifeSpan: "12 - 15 years",
    bredFor: "Herding livestock",
    perfectFor: "Sports, obedience and active families",
    history: "Desenvolvida para conduzir rebanhos com precisao e alta capacidade de resposta.",
    countryCode: "GB",
    weightMinKg: 14,
    weightMaxKg: 20,
    heightReferenceCm: "46 - 56 cm",
    heightMinCm: 46,
    heightMaxCm: 56,
    referenceImageUrl: null,
  },
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    breedGroup: "Sporting",
    origin: "Canada",
    temperament: "Friendly, Outgoing, Active, Trainable, Gentle",
    description: "Companheiro versatil, amigavel e muito popular. Costuma combinar bem com familias e rotinas moderadas.",
    lifeSpan: "10 - 13 years",
    bredFor: "Retrieving game",
    perfectFor: "Families, companionship and guided activities",
    history: "Criado para recuperacao de presas e trabalho ao lado do tutor.",
    countryCode: "CA",
    weightMinKg: 25,
    weightMaxKg: 36,
    heightReferenceCm: "55 - 62 cm",
    heightMinCm: 55,
    heightMaxCm: 62,
    referenceImageUrl: null,
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    breedGroup: "Sporting",
    origin: "Escocia",
    temperament: "Friendly, Intelligent, Reliable, Kind, Trusting",
    description: "Raca conhecida pela docilidade e pela facilidade de convivencia. Exige atencao a exercicio e socializacao.",
    lifeSpan: "10 - 12 years",
    bredFor: "Retrieving waterfowl",
    perfectFor: "Families, companionship and positive training",
    history: "Consolidou-se como raca de trabalho, companhia e apoio em diferentes contextos.",
    countryCode: "GB",
    weightMinKg: 25,
    weightMaxKg: 34,
    heightReferenceCm: "51 - 61 cm",
    heightMinCm: 51,
    heightMaxCm: 61,
    referenceImageUrl: null,
  },
  {
    id: "german-shepherd-dog",
    name: "German Shepherd Dog",
    breedGroup: "Herding",
    origin: "Alemanha",
    temperament: "Confident, Courageous, Intelligent, Loyal, Watchful",
    description: "Raca de trabalho com alta treinabilidade, impulso e presenca. Precisa de conducao firme e bem orientada.",
    lifeSpan: "9 - 13 years",
    bredFor: "Herding and protection",
    perfectFor: "Protection, advanced obedience and active handlers",
    history: "Foi desenvolvida para versatilidade funcional, guarda e obediencia.",
    countryCode: "DE",
    weightMinKg: 22,
    weightMaxKg: 40,
    heightReferenceCm: "55 - 65 cm",
    heightMinCm: 55,
    heightMaxCm: 65,
    referenceImageUrl: null,
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    breedGroup: "Toy",
    origin: "China",
    temperament: "Affectionate, Outgoing, Playful, Friendly",
    description: "Companheiro de pequeno porte, muito proximo da familia e adaptavel a ambientes menores.",
    lifeSpan: "10 - 16 years",
    bredFor: "Companionship",
    perfectFor: "Apartment living and close family companionship",
    history: "Raca tradicionalmente ligada a companhia e convivio proximo com pessoas.",
    countryCode: "CN",
    weightMinKg: 4,
    weightMaxKg: 8,
    heightReferenceCm: "20 - 28 cm",
    heightMinCm: 20,
    heightMaxCm: 28,
    referenceImageUrl: null,
  },
  {
    id: "belgian-malinois",
    name: "Belgian Malinois",
    breedGroup: "Herding",
    origin: "Belgica",
    temperament: "Alert, Intelligent, Protective, Energetic, Responsive",
    description: "Altissima energia e muita prontidao para trabalho. Nao e uma raca para rotina sedentaria.",
    lifeSpan: "12 - 14 years",
    bredFor: "Herding and protection work",
    perfectFor: "Sport, protection and experienced handlers",
    history: "Ganhou destaque moderno em trabalhos de seguranca, esporte e obediencia avancada.",
    countryCode: "BE",
    weightMinKg: 20,
    weightMaxKg: 30,
    heightReferenceCm: "56 - 66 cm",
    heightMinCm: 56,
    heightMaxCm: 66,
    referenceImageUrl: null,
  },
  {
    id: "poodle",
    name: "Poodle",
    breedGroup: "Non-Sporting",
    origin: "Franca",
    temperament: "Intelligent, Trainable, Active, Alert, Proud",
    description: "Raca inteligente, versatil e com grande capacidade de aprendizado. Exige manejo de pelagem.",
    lifeSpan: "12 - 15 years",
    bredFor: "Water retrieval",
    perfectFor: "Families, sports and enriched routines",
    history: "Apesar da imagem de companhia, nasceu com funcao de trabalho e recuperacao na agua.",
    countryCode: "FR",
    weightMinKg: 20,
    weightMaxKg: 32,
    heightReferenceCm: "45 - 60 cm",
    heightMinCm: 45,
    heightMaxCm: 60,
    referenceImageUrl: null,
  },
  {
    id: "bulldog",
    name: "Bulldog",
    breedGroup: "Non-Sporting",
    origin: "Reino Unido",
    temperament: "Docile, Willful, Friendly, Calm",
    description: "Costuma ter energia mais controlada e forte apego a convivencia. Requer atencao especial a saude.",
    lifeSpan: "8 - 10 years",
    bredFor: "Companionship",
    perfectFor: "Calmer routines and family companionship",
    history: "Mudou de uma funcao historica mais dura para um perfil de companhia.",
    countryCode: "GB",
    weightMinKg: 18,
    weightMaxKg: 25,
    heightReferenceCm: "31 - 40 cm",
    heightMinCm: 31,
    heightMaxCm: 40,
    referenceImageUrl: null,
  },
  {
    id: "beagle",
    name: "Beagle",
    breedGroup: "Hound",
    origin: "Reino Unido",
    temperament: "Curious, Friendly, Merry, Determined",
    description: "Raca sociavel e motivada por faro. Pode exigir treino de foco e controle de impulsos.",
    lifeSpan: "12 - 15 years",
    bredFor: "Scent work and hunting",
    perfectFor: "Families that enjoy walks and scent activities",
    history: "Conhecido historicamente por seguir trilhas com persistencia.",
    countryCode: "GB",
    weightMinKg: 9,
    weightMaxKg: 14,
    heightReferenceCm: "33 - 41 cm",
    heightMinCm: 33,
    heightMaxCm: 41,
    referenceImageUrl: null,
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    breedGroup: "Working",
    origin: "Alemanha",
    temperament: "Loyal, Protective, Confident, Calm, Powerful",
    description: "Raca forte, segura e protetora. Precisa de socializacao, conducao responsavel e rotina estruturada.",
    lifeSpan: "9 - 10 years",
    bredFor: "Guarding and driving cattle",
    perfectFor: "Protection, disciplined routines and experienced handlers",
    history: "Associada a trabalho de guarda, conducao e servico.",
    countryCode: "DE",
    weightMinKg: 35,
    weightMaxKg: 60,
    heightReferenceCm: "56 - 69 cm",
    heightMinCm: 56,
    heightMaxCm: 69,
    referenceImageUrl: null,
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    breedGroup: "Toy",
    origin: "Reino Unido",
    temperament: "Sprightly, Affectionate, Alert, Courageous",
    description: "Pequeno no porte, mas atento e cheio de personalidade. Gosta de proximidade com o tutor.",
    lifeSpan: "11 - 15 years",
    bredFor: "Companionship and vermin control",
    perfectFor: "Compact homes and active companionship",
    history: "Surgiu com funcao utilitaria e se consolidou como raca de companhia.",
    countryCode: "GB",
    weightMinKg: 2,
    weightMaxKg: 4,
    heightReferenceCm: "18 - 23 cm",
    heightMinCm: 18,
    heightMaxCm: 23,
    referenceImageUrl: null,
  },
  {
    id: "dachshund",
    name: "Dachshund",
    breedGroup: "Hound",
    origin: "Alemanha",
    temperament: "Clever, Lively, Independent, Brave",
    description: "Conhecido no Brasil como salsicha. Tem iniciativa forte e precisa de rotina com limites claros.",
    lifeSpan: "12 - 16 years",
    bredFor: "Hunting badgers",
    perfectFor: "Families wanting a compact dog with personality",
    history: "Foi desenvolvida para caca em tocas, o que explica sua coragem e insistencia.",
    countryCode: "DE",
    weightMinKg: 7,
    weightMaxKg: 15,
    heightReferenceCm: "13 - 23 cm",
    heightMinCm: 13,
    heightMaxCm: 23,
    referenceImageUrl: null,
  },
  {
    id: "siberian-husky",
    name: "Siberian Husky",
    breedGroup: "Working",
    origin: "Russia",
    temperament: "Outgoing, Friendly, Energetic, Mischievous",
    description: "Raca resistente e muito ativa. Vai melhor em rotinas com exercicio consistente e ambiente enriquecido.",
    lifeSpan: "12 - 14 years",
    bredFor: "Sled pulling",
    perfectFor: "Sporty homes and active outdoor routines",
    history: "Ligada historicamente a tracao e trabalho em clima frio.",
    countryCode: "RU",
    weightMinKg: 16,
    weightMaxKg: 27,
    heightReferenceCm: "50 - 60 cm",
    heightMinCm: 50,
    heightMaxCm: 60,
    referenceImageUrl: null,
  },
  {
    id: "doberman-pinscher",
    name: "Doberman Pinscher",
    breedGroup: "Working",
    origin: "Alemanha",
    temperament: "Alert, Fearless, Loyal, Energetic, Responsive",
    description: "Raca atletica, vigilante e intensa. Se beneficia de treinamento consistente e boa conducao.",
    lifeSpan: "10 - 12 years",
    bredFor: "Protection and personal guard work",
    perfectFor: "Protection sports and focused handlers",
    history: "Consolidou-se como raca de guarda e servico.",
    countryCode: "DE",
    weightMinKg: 27,
    weightMaxKg: 45,
    heightReferenceCm: "61 - 72 cm",
    heightMinCm: 61,
    heightMaxCm: 72,
    referenceImageUrl: null,
  },
  {
    id: "pug",
    name: "Pug",
    breedGroup: "Toy",
    origin: "China",
    temperament: "Charming, Playful, Loving, Stable",
    description: "Companheiro carinhoso e bem presente na rotina da casa. Demanda cuidado respiratorio e controle de peso.",
    lifeSpan: "12 - 15 years",
    bredFor: "Companionship",
    perfectFor: "Companion homes and lighter exercise routines",
    history: "Historicamente ligado a companhia proxima e vida domestica.",
    countryCode: "CN",
    weightMinKg: 6,
    weightMaxKg: 8,
    heightReferenceCm: "25 - 33 cm",
    heightMinCm: 25,
    heightMaxCm: 33,
    referenceImageUrl: null,
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    breedGroup: "Toy",
    origin: "Mexico",
    temperament: "Alert, Quick, Devoted, Lively",
    description: "Pequeno, vigilante e com vinculo forte com o tutor. Pode ser sensivel a manejo e socializacao.",
    lifeSpan: "12 - 18 years",
    bredFor: "Companionship",
    perfectFor: "Compact homes and close human bonding",
    history: "Raca tradicionalmente associada a companhia em ambientes menores.",
    countryCode: "MX",
    weightMinKg: 1,
    weightMaxKg: 3,
    heightReferenceCm: "15 - 23 cm",
    heightMinCm: 15,
    heightMaxCm: 23,
    referenceImageUrl: null,
  },
  {
    id: "samoyed",
    name: "Samoyed",
    breedGroup: "Working",
    origin: "Russia",
    temperament: "Friendly, Gentle, Adaptable, Alert",
    description: "Raca com expressao marcante, boa sociabilidade e necessidade de exercicio e manejo de pelagem.",
    lifeSpan: "12 - 14 years",
    bredFor: "Herding and sled work",
    perfectFor: "Active families with time for grooming",
    history: "Desenvolvida para trabalho e convivencia em clima frio.",
    countryCode: "RU",
    weightMinKg: 16,
    weightMaxKg: 29,
    heightReferenceCm: "48 - 60 cm",
    heightMinCm: 48,
    heightMaxCm: 60,
    referenceImageUrl: null,
  },
  {
    id: "akita",
    name: "Akita",
    breedGroup: "Working",
    origin: "Japao",
    temperament: "Dignified, Courageous, Alert, Loyal, Independent",
    description: "Raca reservada e protetora, com manejo que exige consistencia, leitura comportamental e responsabilidade.",
    lifeSpan: "10 - 13 years",
    bredFor: "Guarding and big game hunting",
    perfectFor: "Experienced homes with structured routines",
    history: "Tem base historica ligada a guarda e atividades de maior exigencia.",
    countryCode: "JP",
    weightMinKg: 24,
    weightMaxKg: 59,
    heightReferenceCm: "58 - 71 cm",
    heightMinCm: 58,
    heightMaxCm: 71,
    referenceImageUrl: null,
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    breedGroup: "Non-Sporting",
    origin: "Japao",
    temperament: "Alert, Active, Independent, Clean",
    description: "Raca autonoma, observadora e com personalidade forte. Vai melhor com treino consistente e respeito ao perfil.",
    lifeSpan: "12 - 15 years",
    bredFor: "Hunting",
    perfectFor: "Tutors who enjoy independent dogs and guided routines",
    history: "Originou-se em atividades de caca e manteve forte senso de autonomia.",
    countryCode: "JP",
    weightMinKg: 7,
    weightMaxKg: 11,
    heightReferenceCm: "35 - 43 cm",
    heightMinCm: 35,
    heightMaxCm: 43,
    referenceImageUrl: null,
  },
  {
    id: "lhasa-apso",
    name: "Lhasa Apso",
    breedGroup: "Non-Sporting",
    origin: "Tibete",
    temperament: "Alert, Confident, Independent, Smart",
    description: "Pequeno porte com personalidade firme. Pode ser otimo companheiro quando bem conduzido.",
    lifeSpan: "12 - 15 years",
    bredFor: "Watchdog and companionship",
    perfectFor: "Homes wanting a compact and attentive companion",
    history: "Historicamente ligado a vigilancia em ambiente interno e companhia.",
    countryCode: "CN",
    weightMinKg: 5,
    weightMaxKg: 8,
    heightReferenceCm: "25 - 28 cm",
    heightMinCm: 25,
    heightMaxCm: 28,
    referenceImageUrl: null,
  },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    breedGroup: "Toy",
    origin: "Reino Unido",
    temperament: "Affectionate, Gentle, Friendly, Adaptable",
    description: "Raca doce, proxima da familia e com boa adaptacao a convivio domestico equilibrado.",
    lifeSpan: "9 - 14 years",
    bredFor: "Companionship",
    perfectFor: "Family companionship and calm routines",
    history: "Tem base historica muito ligada a companhia humana.",
    countryCode: "GB",
    weightMinKg: 6,
    weightMaxKg: 8,
    heightReferenceCm: "30 - 33 cm",
    heightMinCm: 30,
    heightMaxCm: 33,
    referenceImageUrl: null,
  },
  {
    id: "miniature-pinscher",
    name: "Miniature Pinscher",
    breedGroup: "Toy",
    origin: "Alemanha",
    temperament: "Fearless, Energetic, Proud, Alert",
    description: "Pequeno, agil e cheio de presenca. Precisa de gasto mental e limites claros no dia a dia.",
    lifeSpan: "12 - 16 years",
    bredFor: "Companionship and vermin control",
    perfectFor: "Compact homes with consistent handling",
    history: "Manteve energia e prontidao apesar do porte reduzido.",
    countryCode: "DE",
    weightMinKg: 3,
    weightMaxKg: 5,
    heightReferenceCm: "25 - 32 cm",
    heightMinCm: 25,
    heightMaxCm: 32,
    referenceImageUrl: null,
  },
  {
    id: "great-dane",
    name: "Great Dane",
    breedGroup: "Working",
    origin: "Alemanha",
    temperament: "Friendly, Courageous, Patient, Dependable",
    description: "Gigante gentil quando bem conduzido. Exige espaco, manejo e atencao ao crescimento e articulacoes.",
    lifeSpan: "7 - 10 years",
    bredFor: "Guarding and hunting",
    perfectFor: "Spacious homes with responsible handling",
    history: "Raca historicamente ligada a guarda e imponencia funcional.",
    countryCode: "DE",
    weightMinKg: 45,
    weightMaxKg: 79,
    heightReferenceCm: "71 - 86 cm",
    heightMinCm: 71,
    heightMaxCm: 86,
    referenceImageUrl: null,
  },
  {
    id: "cane-corso",
    name: "Cane Corso",
    breedGroup: "Working",
    origin: "Italia",
    temperament: "Protective, Stable, Alert, Powerful, Reserved",
    description: "Raca robusta e protetora, com necessidade real de socializacao, leitura e comando qualificado.",
    lifeSpan: "9 - 12 years",
    bredFor: "Guarding and protection",
    perfectFor: "Experienced handlers and disciplined routines",
    history: "Tem base forte em guarda, presenca e trabalho funcional.",
    countryCode: "IT",
    weightMinKg: 38,
    weightMaxKg: 50,
    heightReferenceCm: "58 - 70 cm",
    heightMinCm: 58,
    heightMaxCm: 70,
    referenceImageUrl: null,
  },
  {
    id: "american-pit-bull-terrier",
    name: "American Pit Bull Terrier",
    breedGroup: "Terrier",
    origin: "Estados Unidos",
    temperament: "Strong, Energetic, Loyal, Determined, Affectionate",
    description: "Raca atletica e intensa, que pede manejo consciente, socializacao e rotina fisica de qualidade.",
    lifeSpan: "12 - 14 years",
    bredFor: "Companion work and athletic activities",
    perfectFor: "Active homes with responsible training",
    history: "Hoje e muito associada a esporte, companhia e manejo comportamental responsavel.",
    countryCode: "US",
    weightMinKg: 14,
    weightMaxKg: 30,
    heightReferenceCm: "43 - 53 cm",
    heightMinCm: 43,
    heightMaxCm: 53,
    referenceImageUrl: null,
  },
  {
    id: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    breedGroup: "Terrier",
    origin: "Reino Unido",
    temperament: "Energetic, Bold, Clever, Tenacious, Alert",
    description: "Pequeno no tamanho, grande na energia. Precisa de ocupacao, treino e rotina ativa.",
    lifeSpan: "13 - 16 years",
    bredFor: "Fox hunting",
    perfectFor: "Highly active homes and playful routines",
    history: "Tem origem em trabalho de campo e conserva forte disposicao para atividade.",
    countryCode: "GB",
    weightMinKg: 5,
    weightMaxKg: 8,
    heightReferenceCm: "25 - 38 cm",
    heightMinCm: 25,
    heightMaxCm: 38,
    referenceImageUrl: null,
  },
]
