// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/[clientId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/[clientId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/[clientId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/companies/[companyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies/[companyId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/companies/[companyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/courses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/courses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dogs/[dogId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dogs/[dogId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dogs/[dogId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dogs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../src/app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/admin/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security">> = Specific
  const handler = {} as typeof import("../../src/app/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/trainings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trainings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/trainings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/traninings/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/traninings/news">> = Specific
  const handler = {} as typeof import("../../src/app/admin/traninings/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/traninings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/traninings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/traninings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agendamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agendamento">> = Specific
  const handler = {} as typeof import("../../src/app/agendamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/new">> = Specific
  const handler = {} as typeof import("../../src/app/blog/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/reels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/reels">> = Specific
  const handler = {} as typeof import("../../src/app/blog/reels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/new">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contato">> = Specific
  const handler = {} as typeof import("../../src/app/contato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/conteudos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conteudos/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/conteudos/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/conteudos/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conteudos/new">> = Specific
  const handler = {} as typeof import("../../src/app/conteudos/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/conteudos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conteudos">> = Specific
  const handler = {} as typeof import("../../src/app/conteudos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/[courseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/courses/[courseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../src/app/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dogs/[dogId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dogs/[dogId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dogs/[dogId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dogs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-policy">> = Specific
  const handler = {} as typeof import("../../src/app/data-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dogs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dogs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dogs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dogs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dogs/new">> = Specific
  const handler = {} as typeof import("../../src/app/dogs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dogs">> = Specific
  const handler = {} as typeof import("../../src/app/dogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/estrutura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estrutura">> = Specific
  const handler = {} as typeof import("../../src/app/estrutura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/forum/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/channels/[slug]/assinar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/channels/[slug]/assinar">> = Specific
  const handler = {} as typeof import("../../src/app/forum/channels/[slug]/assinar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/channels/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/channels/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/forum/channels/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/channels/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/channels/new">> = Specific
  const handler = {} as typeof import("../../src/app/forum/channels/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/new">> = Specific
  const handler = {} as typeof import("../../src/app/forum/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum">> = Specific
  const handler = {} as typeof import("../../src/app/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/rules">> = Specific
  const handler = {} as typeof import("../../src/app/forum/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/racas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/racas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/racas/comparador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racas/comparador">> = Specific
  const handler = {} as typeof import("../../src/app/racas/comparador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/racas/ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racas/ia">> = Specific
  const handler = {} as typeof import("../../src/app/racas/ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/racas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racas">> = Specific
  const handler = {} as typeof import("../../src/app/racas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/racas/radar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racas/radar">> = Specific
  const handler = {} as typeof import("../../src/app/racas/radar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servicos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servicos">> = Specific
  const handler = {} as typeof import("../../src/app/servicos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre">> = Specific
  const handler = {} as typeof import("../../src/app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/training/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/new">> = Specific
  const handler = {} as typeof import("../../src/app/training/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training">> = Specific
  const handler = {} as typeof import("../../src/app/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../src/app/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/dogs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dogs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/dogs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/promote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/promote">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/promote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/schedules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/schedules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/schedules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/training/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/training/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/training/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/breed-consultant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/breed-consultant">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/breed-consultant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/coach">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/send-email-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-email-verification">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/send-email-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/[slug]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/[slug]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/breed-ai/advice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/breed-ai/advice">> = Specific
  const handler = {} as typeof import("../../src/app/api/breed-ai/advice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dogs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dogs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dogs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dogs/breeds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dogs/breeds">> = Specific
  const handler = {} as typeof import("../../src/app/api/dogs/breeds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dogs/recognize-breed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dogs/recognize-breed">> = Specific
  const handler = {} as typeof import("../../src/app/api/dogs/recognize-breed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dogs">> = Specific
  const handler = {} as typeof import("../../src/app/api/dogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/[id]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/[id]/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/[id]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/[id]/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/[id]/reply">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/[id]/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/channels/[channelId]/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/channels/[channelId]/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/channels/[channelId]/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/channels">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/image">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/video">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify/email/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify/email/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify/email/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify/email/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify/email/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify/email/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify/email/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify/email/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify/email/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify/phone/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify/phone/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify/phone/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify/phone/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify/phone/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify/phone/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
