services:
  app:
    build: .
    container_name: k9_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: k9_db
    restart: always
    environment:
      POSTGRES_USER: devStartp
      POSTGRES_PASSWORD: 1533
      POSTGRES_DB: devStartp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
