var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/dogs/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ef477b32._.js")
R.c("server/chunks/ssr/_74eb00cd._.js")
R.c("server/chunks/ssr/_f19599fc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_dbead00f._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6a2bcbe4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dogs_page_actions_97df6b51.js")
R.m(58485)
module.exports=R.m(58485).exports
