var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dogs/[id]/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3f9d83e7._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_9770598e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6a2bcbe4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dogs_[id]_edit_page_actions_a29251a6.js")
R.m(57812)
module.exports=R.m(57812).exports
