var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/traninings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__307d0a08._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_465c1fc5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c57189c0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_9cb4d248._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_traninings_page_actions_c4178ecf.js")
R.m(56589)
module.exports=R.m(56589).exports
