// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/clients" | "/admin/clients/[clientId]" | "/admin/companies" | "/admin/companies/[companyId]" | "/admin/courses" | "/admin/courses/new" | "/admin/dogs" | "/admin/dogs/[dogId]" | "/admin/finance" | "/admin/schedule" | "/admin/security" | "/admin/trainings" | "/admin/traninings" | "/admin/traninings/news" | "/admin/users" | "/admin/users/[userId]" | "/agendamento" | "/billing" | "/blog" | "/blog/[slug]" | "/blog/new" | "/calendar" | "/calendar/new" | "/contato" | "/conteudos" | "/conteudos/[slug]" | "/conteudos/new" | "/courses" | "/courses/[courseId]" | "/dashboard" | "/dashboard/dogs" | "/dashboard/dogs/[dogId]" | "/data-policy" | "/dogs" | "/dogs/[id]/edit" | "/dogs/new" | "/estrutura" | "/forum" | "/forum/[id]" | "/forum/channels/[slug]" | "/forum/channels/new" | "/forum/new" | "/forum/rules" | "/login" | "/profile" | "/profile/edit" | "/racas" | "/register" | "/servicos" | "/sobre" | "/training" | "/training/[sessionId]" | "/training/new" | "/verify"
type AppRouteHandlerRoutes = "/api/admin/dogs/[id]" | "/api/admin/promote" | "/api/admin/schedules/[id]" | "/api/admin/training/[id]" | "/api/admin/users/[id]" | "/api/admin/users/[id]/approve" | "/api/admin/users/[id]/reject" | "/api/ai/breed-consultant" | "/api/ai/coach" | "/api/auth" | "/api/auth/[...nextauth]" | "/api/auth/send-email-verification" | "/api/billing/checkout" | "/api/billing/plan" | "/api/blog" | "/api/blog/[slug]" | "/api/blog/[slug]/comments" | "/api/blog/[slug]/reactions" | "/api/breed-ai/advice" | "/api/content" | "/api/dogs" | "/api/dogs/[id]" | "/api/dogs/breeds" | "/api/dogs/recognize-breed" | "/api/forum" | "/api/forum/[id]" | "/api/forum/[id]/reactions" | "/api/forum/[id]/reply" | "/api/forum/channels" | "/api/forum/channels/[channelId]/subscription" | "/api/login" | "/api/profile" | "/api/register" | "/api/schedule" | "/api/stripe/webhook" | "/api/training" | "/api/upload/image" | "/api/upload/video" | "/api/users" | "/api/verify/email/confirm" | "/api/verify/email/request" | "/api/verify/email/verify" | "/api/verify/phone/confirm" | "/api/verify/phone/request"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/clients": {}
  "/admin/clients/[clientId]": { "clientId": string; }
  "/admin/companies": {}
  "/admin/companies/[companyId]": { "companyId": string; }
  "/admin/courses": {}
  "/admin/courses/new": {}
  "/admin/dogs": {}
  "/admin/dogs/[dogId]": { "dogId": string; }
  "/admin/finance": {}
  "/admin/schedule": {}
  "/admin/security": {}
  "/admin/trainings": {}
  "/admin/traninings": {}
  "/admin/traninings/news": {}
  "/admin/users": {}
  "/admin/users/[userId]": { "userId": string; }
  "/agendamento": {}
  "/api/admin/dogs/[id]": { "id": string; }
  "/api/admin/promote": {}
  "/api/admin/schedules/[id]": { "id": string; }
  "/api/admin/training/[id]": { "id": string; }
  "/api/admin/users/[id]": { "id": string; }
  "/api/admin/users/[id]/approve": { "id": string; }
  "/api/admin/users/[id]/reject": { "id": string; }
  "/api/ai/breed-consultant": {}
  "/api/ai/coach": {}
  "/api/auth": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/send-email-verification": {}
  "/api/billing/checkout": {}
  "/api/billing/plan": {}
  "/api/blog": {}
  "/api/blog/[slug]": { "slug": string; }
  "/api/blog/[slug]/comments": { "slug": string; }
  "/api/blog/[slug]/reactions": { "slug": string; }
  "/api/breed-ai/advice": {}
  "/api/content": {}
  "/api/dogs": {}
  "/api/dogs/[id]": { "id": string; }
  "/api/dogs/breeds": {}
  "/api/dogs/recognize-breed": {}
  "/api/forum": {}
  "/api/forum/[id]": { "id": string; }
  "/api/forum/[id]/reactions": { "id": string; }
  "/api/forum/[id]/reply": { "id": string; }
  "/api/forum/channels": {}
  "/api/forum/channels/[channelId]/subscription": { "channelId": string; }
  "/api/login": {}
  "/api/profile": {}
  "/api/register": {}
  "/api/schedule": {}
  "/api/stripe/webhook": {}
  "/api/training": {}
  "/api/upload/image": {}
  "/api/upload/video": {}
  "/api/users": {}
  "/api/verify/email/confirm": {}
  "/api/verify/email/request": {}
  "/api/verify/email/verify": {}
  "/api/verify/phone/confirm": {}
  "/api/verify/phone/request": {}
  "/billing": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/new": {}
  "/calendar": {}
  "/calendar/new": {}
  "/contato": {}
  "/conteudos": {}
  "/conteudos/[slug]": { "slug": string; }
  "/conteudos/new": {}
  "/courses": {}
  "/courses/[courseId]": { "courseId": string; }
  "/dashboard": {}
  "/dashboard/dogs": {}
  "/dashboard/dogs/[dogId]": { "dogId": string; }
  "/data-policy": {}
  "/dogs": {}
  "/dogs/[id]/edit": { "id": string; }
  "/dogs/new": {}
  "/estrutura": {}
  "/forum": {}
  "/forum/[id]": { "id": string; }
  "/forum/channels/[slug]": { "slug": string; }
  "/forum/channels/new": {}
  "/forum/new": {}
  "/forum/rules": {}
  "/login": {}
  "/profile": {}
  "/profile/edit": {}
  "/racas": {}
  "/register": {}
  "/servicos": {}
  "/sobre": {}
  "/training": {}
  "/training/[sessionId]": { "sessionId": string; }
  "/training/new": {}
  "/verify": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
