var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/sobre/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__eadd0e58._.js")
R.c("server/chunks/ssr/_6210eed7._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_95d7f5a5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c57189c0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_sobre_page_actions_4fa689a5.js")
R.m(51354)
module.exports=R.m(51354).exports
