var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/training/[sessionId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fa38b7eb._.js")
R.c("server/chunks/ssr/_9942416a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_dbead00f._.js")
R.c("server/chunks/ssr/_f19599fc._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6a2bcbe4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8df4800f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_training_[sessionId]_page_actions_7aeb6a09.js")
R.m(22423)
module.exports=R.m(22423).exports
